package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("application", "id", Application.class);
		arp.addMapping("expressthanks", "id", Expressthanks.class);
		arp.addMapping("lostthings", "id", Lostthings.class);
		arp.addMapping("notice", "id", Notice.class);
		arp.addMapping("pickthings", "id", Pickthings.class);
		arp.addMapping("student", "stuId", Student.class);
		arp.addMapping("type", "id", Type.class);
	}
}

