package model;

import model.base.BaseApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Application extends BaseApplication<Application> {
	public static final Application dao = new Application().dao();
}
