package model;

import model.base.BaseExpressthanks;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Expressthanks extends BaseExpressthanks<Expressthanks> {
	public static final Expressthanks dao = new Expressthanks().dao();
}
