package model;

import model.base.BaseLostthings;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lostthings extends BaseLostthings<Lostthings> {
	public static final Lostthings dao = new Lostthings().dao();
}
