package model;

import model.base.BasePickthings;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pickthings extends BasePickthings<Pickthings> {
	public static final Pickthings dao = new Pickthings().dao();
}
