package model;

import model.base.BaseThingtype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Thingtype extends BaseThingtype<Thingtype> {
	public static final Thingtype dao = new Thingtype().dao();
}
