package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExpressthanks<M extends BaseExpressthanks<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setStuId(java.lang.Integer stuId) {
		set("stuId", stuId);
		return (M)this;
	}
	
	public java.lang.Integer getStuId() {
		return getInt("stuId");
	}

	public M setLeaveTime(java.util.Date leaveTime) {
		set("leaveTime", leaveTime);
		return (M)this;
	}
	
	public java.util.Date getLeaveTime() {
		return get("leaveTime");
	}

}
