package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLostthings<M extends BaseLostthings<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setThingsName(java.lang.String thingsName) {
		set("thingsName", thingsName);
		return (M)this;
	}
	
	public java.lang.String getThingsName() {
		return getStr("thingsName");
	}

	public M setLostPlace(java.lang.String lostPlace) {
		set("lostPlace", lostPlace);
		return (M)this;
	}
	
	public java.lang.String getLostPlace() {
		return getStr("lostPlace");
	}

	public M setLostTime(java.util.Date lostTime) {
		set("lostTime", lostTime);
		return (M)this;
	}
	
	public java.util.Date getLostTime() {
		return get("lostTime");
	}

	public M setThingsType(java.lang.Integer thingsType) {
		set("thingsType", thingsType);
		return (M)this;
	}
	
	public java.lang.Integer getThingsType() {
		return getInt("thingsType");
	}

	public M setThingsImg(java.lang.String thingsImg) {
		set("thingsImg", thingsImg);
		return (M)this;
	}
	
	public java.lang.String getThingsImg() {
		return getStr("thingsImg");
	}

	public M setThingsDetail(java.lang.String thingsDetail) {
		set("thingsDetail", thingsDetail);
		return (M)this;
	}
	
	public java.lang.String getThingsDetail() {
		return getStr("thingsDetail");
	}

	public M setPublishTime(java.util.Date publishTime) {
		set("publishTime", publishTime);
		return (M)this;
	}
	
	public java.util.Date getPublishTime() {
		return get("publishTime");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setStuId(java.lang.Integer stuId) {
		set("stuId", stuId);
		return (M)this;
	}
	
	public java.lang.Integer getStuId() {
		return getInt("stuId");
	}

}
