package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApplication<M extends BaseApplication<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPickId(java.lang.Integer pickId) {
		set("pickId", pickId);
		return (M)this;
	}
	
	public java.lang.Integer getPickId() {
		return getInt("pickId");
	}

	public M setStuId(java.lang.Integer stuId) {
		set("stuId", stuId);
		return (M)this;
	}
	
	public java.lang.Integer getStuId() {
		return getInt("stuId");
	}

	public M setApplyTime(java.util.Date applyTime) {
		set("applyTime", applyTime);
		return (M)this;
	}
	
	public java.util.Date getApplyTime() {
		return get("applyTime");
	}

}
